import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { SafeList } from './components/SafeList'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>safe-viewer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>safe-viewer</h1>
        <SafeList />
      </main>
    </div>
  )
}

export default Home
